controllers:
  arm_controller:
    type: JointTrajectoryActionController
    joint_trajectory_action_node:
      min_velocity: 0.1
      constraints:
        goal_time: 0.05
    joint_controllers:
      - "joint1_controller"
      - "joint2_controller"
      - "joint3_controller"
      - "joint4_controller"
      - "joint5_controller"

#  gripper_controller:
#    type: JointTrajectoryActionController
#    joint_trajectory_action_node:
#      min_velocity: 0.1
#      constraints:
#        goal_time: 0.05
#    joint_controllers:
#      - "r_joint_controller"